/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (57.28%)
 * Likes:    1055
 * Dislikes: 301
 * Total Accepted:    236.8K
 * Total Submissions: 413.1K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 * Example 1:
 *
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 *
 * Example 2:
 *
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Example 3:
 *
 *
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 *
 * Example 4:
 *
 *
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 *
 *
 * Constraints:
 *
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 *
 *
 */

// @lc code=start
class Solution {
public:
    char findTheDifference(string s, string t) {
        int cnt[26] = {0};
        for (auto c : s) {
            cnt[c-'a']++;
        }
        for (auto c : t) {
            cnt[c-'a']--;
        }
        for (int i = 0; i < 26; i++) {
            if(cnt[i]) {
                return 'a'+i;
            }
        }
        return '\0';
    }
};
// @lc code=end

/* XXX
class Solution {
public:
    char findTheDifference(string s, string t) {
        char x=0;
        for(auto i:s) x^=i;
        for(auto i:t) x^=i;
        return x;
    }
};
*/
